/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtWho: typeof import('./src/components/at-who/index.vue')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    Example1: typeof import('./src/components/my-menu/demo/examples/Example1.vue')['default']
    MyContainer: typeof import('./src/components/my-container/index.vue')['default']
    MyFullCalender: typeof import('./src/components/my-full-calender/index.vue')['default']
    MyGantt: typeof import('./src/components/my-gantt/index.vue')['default']
    MyMention: typeof import('./src/components/my-mention/index.vue')['default']
    MyMenu: typeof import('./src/components/my-menu/index.vue')['default']
    MyMenuItem: typeof import('./src/components/my-menu/my-menu-item.vue')['default']
    MySubmenu: typeof import('./src/components/my-menu/my-submenu.vue')['default']
    MyTab: typeof import('./src/components/my-tab/index.vue')['default']
    MyTestComp: typeof import('./src/components/my-test-comp/index.vue')['default']
    MyUButton: typeof import('./src/components/my-u-button/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabItem: typeof import('./src/components/my-tab/tab-item.vue')['default']
    Theme: typeof import('./src/components/my-u-button/theme/index.vue')['default']
  }
}
